### ISSUE TITLE
Simplify readme.md

### ISSUE THREAD

**Issue by abeggchr** [Zuehlke/zuehlke-book#12]

**Comment by bruderol** [comment]
I am working on the last TODOs and some simplification

**Comment by abeggchr** [comment]
created pull request
ready to go?

**Comment by bruderol** [comment]
@abeggchr sorry, was too busy, I will give you some feedback today. I had some pending changes open, that I will try to merge now.

**Comment by bruderol** [comment]
@abeggchr please see my two commits on the Pull Request #15: I overworked the README.md as well and merged my changes with yours and tried to improve even more such that it should be now understandable for everybody, even without git or github know how.

Can you please read through everything once again - Is it okay like that?

I think now we can go for a test run with these explanations.
Or what do you think? Is something missing?

**Comment by abeggchr** [comment]
I think now we can go for a test run with these explanations.
