### ISSUE TITLE
Size of the article (min / max)

### ISSUE THREAD

**Issue by abeggchr** [Zuehlke/zuehlke-book#13]
approxximatively 2 A5 pages

determine
controlloing (i.e. test)

**Comment by abeggchr** [comment]
97 things has:
min: 415 words 2,431 characters
max: 743 words 4,113 characters

used the following gulp script:
```
var gulp = require("gulp");
var countStat = require("gulp-count-stat");

gulp.task("stat", function () {
    return gulp.src("thing_*/README.md")
        .pipe(countStat());
});
```

**Comment by bruderol** [comment]
I proposed now to allow a maximum of approximately 2 A4 pages - but we can still make is more strict. 

If you want we could as well setup a build to check this very strict rules. 

But I am not sure whether it is a good idea to be so strict about the length right from the start as long as we do not print it yet. We might keep that open and then shorten the articles when we go for a printed version of selected acrticles.

**Comment by abeggchr** [comment]
"short enough to be read in 10 minutes: size should be less than 2 A4 pages long in printout PDF version."

I don't think 2 A4 pages can be read in 10 minutes. 1 A4 page?

**Comment by bruderol** [comment]
I think we should not restrict the length too much. But why not just wait, write some first articles and then discuss about what is a typical good size of a valuable article.

**Comment by abeggchr** [comment]
ok
