### ISSUE TITLE
Article: When is a build system a build system?

### ISSUE THREAD

**Issue by damphyr** [Zuehlke/zuehlke-book#26]
3+1 rules for build systems that enable us to easily build CI around them.

The original [blog post](http://www.ampelofilosofies.gr/software/2014/07/17/vars-build-rules) works as a very good summary.

**Comment by damphyr** [comment]
I have a problem finding a book-appropriate title :)

**Comment by abeggchr** [comment]
Freely associating....
- Build server to the rescue
- The (not so hidden) force of a build server
- Treat the build server as a first class teammate
- Make the build your buddy
- About the importance of a build process
- Give the build the force/weight/importance it deserves

Not a match so far, but I hope it gets your ideas sparkling.

**Comment by bruderol** [comment]
+1 for "treat the build server as a first class team member" - if not "as the most important team member" ;-)

**Comment by abeggchr** [comment]
Thanks for your interesting article! 
It is now merged to the Zuehlke repository.
