### ISSUE TITLE
Ideas for Articles (feel free to pick up an idea!)

### ISSUE THREAD

**Issue by peitor** [Zuehlke/zuehlke-book#41]
* beware what you measure

**Comment by abeggchr** [comment]
All models are wrong
cynefin
3fus model of skill acquisition
...
Why should you learn these?
Communication pattern,

**Comment by abeggchr** [comment]
"No magic"

Avoid tools that are magic.
Don't use technologies that you don't understand.
Don't use technologies that hide too many abstractions.
Mention abstractions?

**Comment by bruderol** [comment]
@abeggchr can we close this? I think every article idea should simply be opened as an issue on its own, such that it is in the list.

**Comment by bruderol** [comment]
I close this, i opened a article for the abovce missing point by @peitor
