### ISSUE TITLE
@abeggchr configure git correctly for future commits!

### ISSUE THREAD

**Issue by bruderol** [Zuehlke/zuehlke-book#7]
@abeggchr 

your commits do not have appropriate author information set. Your email with which you commited is not properly assigned to your github account!

Either attach the email with which you commited to your github account or otherwise make sure to allways configure your local git correctly, as described here:
* https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup
  or also here: https://github.com/scenarioo/scenarioo/blob/develop/docs/contribute/Development-Environment-with-IntelliJ.md#setup-and-use-of-git
* Also we should configure to use Linux style line endings always, see last scenarioo link as well about that!

Unfortunately if this happen, you will have to rewrite github history for getting your commits assigned to your github account correctly. :-( 

This is probably not worth it, but make sure you use correct configured git client for future commits. Thank you!

We might also have to mention this in our guide for all contributors.

**Comment by bruderol** [comment]
See your commits, e.g. https://github.com/Zuehlke/zuehlke-book/commit/ccf1fed7bccea97d0a32f74c0e0c73979cfe677a - they do not link to your github profile as an author.

**Comment by abeggchr** [comment]
Attached the email to my github account and configured git locally.

**Comment by bruderol** [comment]
Thanks - I think we have to add this to the README for nobody makes the same mistake, changing/correcting this afterwards is almost impossible (especially once it is merged to the major branch), would need to rewrite git history.
